# Generated by Django 2.2.6 on 2019-10-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=25)),
                ('licence', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('storeAddress', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='licence',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('CTS', 'CTS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
