# Generated by Django 2.2.6 on 2019-10-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_company_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.CharField(choices=[("MA'S", "MA'S"), ('CTS', 'CTS')], max_length=15),
        ),
    ]
