# Generated by Django 2.2.6 on 2019-10-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20191030_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
