# Generated by Django 2.2.6 on 2019-11-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacist',
            old_name='pharmacistDrugeLicence',
            new_name='pharmacistDrugLicence',
        ),
    ]
