# Generated by Django 2.2.6 on 2019-11-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0002_auto_20191107_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacist',
            name='pharmacistDrugLicence',
        ),
    ]
