# Generated by Django 2.2.6 on 2019-11-23 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0003_remove_pharmacist_pharmacistdruglicence'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacistDrugLicence',
            field=models.CharField(default=django.utils.timezone.now, max_length=33),
            preserve_default=False,
        ),
    ]
