# Generated by Django 2.2.6 on 2019-11-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0004_pharmacist_pharmacistdruglicence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='pharmacistPhoneNummber',
            field=models.CharField(max_length=18),
        ),
    ]
