# Generated by Django 2.2.6 on 2019-11-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0005_auto_20191123_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacist',
            old_name='pharmacistDrugLicence',
            new_name='drugLicence',
        ),
        migrations.RenameField(
            model_name='pharmacist',
            old_name='pharmacistPassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='pharmacist',
            old_name='pharmacistPhoneNummber',
            new_name='phoneNummber',
        ),
        migrations.RenameField(
            model_name='pharmacist',
            old_name='pharmacistStoreAddress',
            new_name='storeAddress',
        ),
        migrations.RenameField(
            model_name='pharmacist',
            old_name='pharmacistStoreName',
            new_name='storeName',
        ),
    ]
