# Generated by Django 2.2.6 on 2019-11-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0011_auto_20191128_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
