# Generated by Django 2.2.6 on 2019-11-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0014_auto_20191130_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
