# Generated by Django 2.2.6 on 2019-11-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
        ('Pharmacist', '0015_auto_20191130_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldMedicine',
            fields=[
                ('soldMedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('medicineQuantity', models.CharField(max_length=20)),
                ('soldDate', models.DateField()),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacist.Pharmacist')),
                ('prescribedMedicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.PrescribedMedicine')),
            ],
        ),
    ]
