# Generated by Django 2.2.6 on 2019-11-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0016_soldmedicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestock',
            name='quantity',
            field=models.IntegerField(max_length=50),
        ),
    ]
