# Generated by Django 2.2.6 on 2019-11-30 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0017_auto_20191201_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldmedicine',
            name='soldDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
