# Generated by Django 2.2.6 on 2019-12-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20191105_1955'),
        ('Pharmacist', '0018_auto_20191201_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldMedicineWithoutPrescription',
            fields=[
                ('soldMedicineWithoutPrescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(max_length=50)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Medicine')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacist.Pharmacist')),
            ],
        ),
    ]
