# Generated by Django 2.2.6 on 2019-12-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0019_soldmedicinewithoutprescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(max_length=20),
        ),
    ]
