# Generated by Django 2.2.6 on 2019-11-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBloodGroup',
            fields=[
                ('patientBloodGroupId', models.AutoField(primary_key=True, serialize=False)),
                ('patientBloodGroupName', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSex',
            fields=[
                ('patientSexId', models.AutoField(primary_key=True, serialize=False)),
                ('patientSexName', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=44)),
                ('patientDateOfBirth', models.DateField()),
                ('patientPhoneNumber', models.BigIntegerField(max_length=16)),
                ('patientPassword', models.CharField(max_length=33)),
                ('patientBloodGroup', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Patient.PatientBloodGroup')),
                ('patientSex', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Patient.PatientSex')),
            ],
        ),
    ]
