# Generated by Django 2.2.6 on 2019-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=44)),
                ('patientDateOfBirth', models.DateField()),
                ('patientSex', models.CharField(max_length=33)),
                ('patientPhoneNumber', models.BigIntegerField(max_length=16)),
                ('patientBloodGroup', models.CharField(max_length=5)),
                ('patientPassword', models.CharField(max_length=33)),
            ],
        ),
    ]
