# Generated by Django 2.2.6 on 2019-11-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='prescribedMedicineQuantity',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='prescribedMedicineTakenQuantity',
            field=models.IntegerField(max_length=11),
        ),
    ]
