# Generated by Django 2.2.6 on 2019-11-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientBloodGroupName', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientSexName', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientBloodGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Patient.PatientBloodGroup'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientSex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Patient.PatientSex'),
        ),
    ]
