# Generated by Django 2.2.6 on 2019-11-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20191105_1955'),
        ('Patient', '0002_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('prescribedMedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('prescribedMedicineFrequancy', models.CharField(max_length=11)),
                ('prescribedMedicineFrequancyQuantity', models.CharField(max_length=11)),
                ('prescribedMedicineDuration', models.CharField(max_length=11)),
                ('prescribedMedicineQuantity', models.CharField(max_length=11)),
                ('prescribedMedicineTakenQuantity', models.CharField(max_length=11)),
                ('prescribedMedicineMedicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Medicine')),
                ('prescribedMedicinePrescriptioin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Prescription')),
            ],
        ),
    ]
