# Generated by Django 2.2.6 on 2019-11-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientPhoneNumber',
            field=models.CharField(max_length=16),
        ),
    ]
