# Generated by Django 2.2.6 on 2019-11-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='formId',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='typeId',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='companyId',
        ),
        migrations.AddField(
            model_name='medicine',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Company.Company'),
            preserve_default=False,
        ),
    ]
