# Generated by Django 2.2.6 on 2019-11-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20191102_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(choices=[("MA'S", "MA'S"), ('CTS', 'CTS')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
