# Generated by Django 2.2.6 on 2019-11-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(choices=[("MA'S", "MA'S"), ('CTS', 'CTS')], max_length=15)),
                ('type', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
